AWSTemplateFormatVersion: "2010-09-09"

Description: Transit Gateway Deployment for OFX

Resources:
  TransitGateway:
    Type: AWS::EC2::TransitGateway
    Properties: 
      AmazonSideAsn: 64512
      AutoAcceptSharedAttachments: enable
      DefaultRouteTableAssociation: enable
      DefaultRouteTablePropagation: enable
      Description: Transit Gateway Deployment
      DnsSupport: enable
      VpnEcmpSupport: enable

  TransitGatewayResourceShare:
    Type: AWS::RAM::ResourceShare
    Properties: 
      AllowExternalPrincipals: True
      Name: ResourceShare
      Principals: 
        - 925446695292
        - 978308152145
      ResourceArns: 
        - !Join
          - ''
          - - 'arn:aws:ec2:ap-southeast-2:045932084931:transit-gateway/'
            - !Ref TransitGateway

Outputs:
  TransitGateway:
    Description: A reference to the created TransitGateway
    Value: !Ref TransitGateway
    Export:
      Name: !Sub ${AWS::StackName}