AWSTemplateFormatVersion: "2010-09-09"

Description: Transit Gateway Attachment for Account

Resources:
  TransitGatewayAttachment:
    Type: AWS::EC2::TransitGatewayAttachment
    Properties: 
      SubnetIds: 
        - subnet-e73dc191 
        - subnet-82ee3fe6 
        - subnet-21837c78 
        
      TransitGatewayId: tgw-067fc30b039641df1
      VpcId: vpc-881b11ed
      Tags:
        -
          Key: Name
          Value: PipelineDev
      
Outputs:
  TransitGatewayAttachment:
    Description: A reference to the created TransitGatewayAttachment
    Value: !Ref TransitGatewayAttachment
    Export:
      Name: !Sub ${AWS::StackName}
