AWSTemplateFormatVersion: "2010-09-09"

Description: Transit Gateway Attachment for Account

Resources:
  TransitGatewayAttachment:
    Type: AWS::EC2::TransitGatewayAttachment
    Properties: 
      SubnetIds: 
        - subnet-07cfe690b5af033aa 
        - subnet-0e5a118200697b735 
        - subnet-0d5d773637687e808 
        
      TransitGatewayId: tgw-067fc30b039641df1
      VpcId: vpc-00fe835822bd385df
      Tags:
        -
          Key: Name
          Value: KumoClientSandbox
      
Outputs:
  TransitGatewayAttachment:
    Description: A reference to the created TransitGatewayAttachment
    Value: !Ref TransitGatewayAttachment
    Export:
      Name: !Sub ${AWS::StackName}
