AWSTemplateFormatVersion: "2010-09-09"

Description: Transit Gateway Deployment for OFX

Resources:
  TransitGateway:
    Type: AWS::EC2::TransitGateway
    Properties: 
      AmazonSideAsn: 65100
      AutoAcceptSharedAttachments: enable
      DefaultRouteTableAssociation: enable
      DefaultRouteTablePropagation: enable
      Description: Transit Gateway Deployment
      DnsSupport: enable
      VpnEcmpSupport: enable

Outputs:
  TransitGateway:
    Description: A reference to the created TransitGateway
    Value: !Ref TransitGateway
    Export:
      Name: !Sub ${AWS::StackName}
